# Create Vercel Deployment
name: 'Vercel'

on:
  pull_request:
  release:
    types:
      - 'published'

jobs:
  deployment:
    name: 'Deployment'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Vercel Deployment'
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@20
        with:
          vercel-token: ${{ secrets.VERCEL_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

      - name: 'Vercel Production'
        if: github.event_name == 'release' && github.event_name.action == 'published'
        uses: amondnet/vercel-action@20
        with:
          vercel-token: ${{ secrets.VERCEL_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod' #Optional
